[package]
name = "skolem"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
build_html = "2.5.0"
itertools = "0.13.0"
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
